"use strict";

const ROLES = Object.freeze({
  PUBLIC: "public",
  SCOUT: "scout",
  PARENT: "parent",
  GUARDIAN: "guardian",
  LEADER: "leader",
  COMMITTEE: "committee",
  ADULT_LEADER: "adult_leader",
  COMMITTEE_MEMBER: "committee_member",
  ADMINISTRATOR: "administrator"
});

const POSITIONS = Object.freeze({
  SCOUTMASTER: "scoutmaster",
  ASSISTANT_SCOUTMASTER: "assistant_scoutmaster",
  QUARTERMASTER: "quartermaster",
  SPL: "SPL"
});

const PERMISSIONS = Object.freeze({
  VIEW_OWN: "view_own",
  VIEW_LINKED_SCOUT: "view_linked_scout",
  EDIT_LINKED_SCOUT: "edit_linked_scout",
  VIEW_ALL_SCOUTS: "view_all_scouts",
  EDIT_ALL_SCOUTS: "edit_all_scouts",
  MANAGE_UNIT: "manage_unit",
  MESSAGING: "messaging"
});

const FIELD_SCOPES = Object.freeze({
  PROFILE: "profile",
  MEDICAL: "medical",
  ADVANCEMENT: "advancement"
});

const PERSON_TYPES = Object.freeze({
  ADULT: "adult",
  SCOUT: "scout"
});

const ROLE_ASSIGNABLE_BY_UNIT = new Set([
  ROLES.PARENT,
  ROLES.GUARDIAN,
  ROLES.LEADER,
  ROLES.COMMITTEE,
  ROLES.ADULT_LEADER,
  ROLES.COMMITTEE_MEMBER
]);

const GLOBAL_ASSIGNABLE_ROLES = new Set([ROLES.ADMINISTRATOR]);

const ROLE_ALIASES = Object.freeze({
  [ROLES.ADULT_LEADER]: ROLES.LEADER,
  [ROLES.COMMITTEE_MEMBER]: ROLES.COMMITTEE
});

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.PUBLIC]: [],
  [ROLES.SCOUT]: [PERMISSIONS.VIEW_OWN, PERMISSIONS.MESSAGING],
  [ROLES.PARENT]: [
    PERMISSIONS.VIEW_OWN,
    PERMISSIONS.VIEW_LINKED_SCOUT,
    PERMISSIONS.EDIT_LINKED_SCOUT,
    PERMISSIONS.MESSAGING
  ],
  [ROLES.GUARDIAN]: [
    PERMISSIONS.VIEW_OWN,
    PERMISSIONS.VIEW_LINKED_SCOUT,
    PERMISSIONS.EDIT_LINKED_SCOUT,
    PERMISSIONS.MESSAGING
  ],
  [ROLES.LEADER]: [PERMISSIONS.VIEW_OWN, PERMISSIONS.VIEW_ALL_SCOUTS, PERMISSIONS.MESSAGING],
  [ROLES.COMMITTEE]: [
    PERMISSIONS.VIEW_OWN,
    PERMISSIONS.VIEW_ALL_SCOUTS,
    PERMISSIONS.MANAGE_UNIT,
    PERMISSIONS.MESSAGING
  ],
  [ROLES.ADMINISTRATOR]: Object.values(PERMISSIONS)
});

const POSITION_PERMISSIONS = Object.freeze({
  [POSITIONS.SCOUTMASTER]: [
    PERMISSIONS.VIEW_OWN,
    PERMISSIONS.VIEW_ALL_SCOUTS,
    PERMISSIONS.EDIT_ALL_SCOUTS,
    PERMISSIONS.MANAGE_UNIT,
    PERMISSIONS.MESSAGING
  ],
  [POSITIONS.ASSISTANT_SCOUTMASTER]: [
    PERMISSIONS.VIEW_OWN,
    PERMISSIONS.VIEW_ALL_SCOUTS,
    PERMISSIONS.MESSAGING
  ],
  [POSITIONS.QUARTERMASTER]: [
    PERMISSIONS.VIEW_OWN,
    PERMISSIONS.VIEW_ALL_SCOUTS,
    PERMISSIONS.MESSAGING
  ],
  [POSITIONS.SPL]: [PERMISSIONS.VIEW_OWN, PERMISSIONS.VIEW_ALL_SCOUTS, PERMISSIONS.MESSAGING]
});

module.exports = {
  FIELD_SCOPES,
  GLOBAL_ASSIGNABLE_ROLES,
  PERMISSIONS,
  PERSON_TYPES,
  POSITIONS,
  POSITION_PERMISSIONS,
  ROLES,
  ROLE_ALIASES,
  ROLE_ASSIGNABLE_BY_UNIT,
  ROLE_PERMISSIONS
};
